const express = require('express');
const Student = require('../models/Student');
const multer = require('multer');
const csv = require('csv-parser');
const fs = require('fs');
const { Parser } = require('json2csv');

const router = express.Router();

// ✅ ADD STUDENT
router.post('/add', async (req, res) => {
  try {
    const {
      sisId,
      name,
      email,
      phone,
      class: className,
      year,
      rollNo,
      enrollmentNo,
      branch
    } = req.body;

    // ✅ Validation
    if (
      !sisId ||
      !name ||
      !email ||
      !phone ||
      !className ||
      !year ||
      !rollNo ||
      !enrollmentNo ||
      !branch
    ) {
      return res.status(400).json({
        message: "All fields are required"
      });
    }

    // ✅ Check duplicate student
    const existingStudent = await Student.findOne({
      $or: [{ sisId }, { email }, { rollNo }, { enrollmentNo }]
    });

    if (existingStudent) {
      return res.status(400).json({
        message: "Student already exists"
      });
    }

    // ✅ Create student (password auto-generated)
    const student = new Student({
      sisId,
      name,
      email,
      phone,
      class: className,
      year,
      rollNo,
      enrollmentNo,
      branch
    });

    await student.save();

    res.status(201).json({
      message: "Student added successfully",
      student: {
        id: student._id,
        sisId: student.sisId,
        name: student.name,
        email: student.email,
        phone: student.phone,
        class: student.class,
        year: student.year,
        rollNo: student.rollNo,
        enrollmentNo: student.enrollmentNo,
        branch: student.branch,
        password: student.password // show only once
      }
    });

  } catch (error) {
    res.status(500).json({
      message: "Server error",
      error: error.message
    });
  }
});


// Multer config
const upload = multer({ dest: 'uploads/' });

// ✅ BULK STUDENT UPLOAD
router.post('/upload-csv', upload.single('file'), async (req, res) => {
  try {
    const students = [];

    fs.createReadStream(req.file.path)
      .pipe(csv())
      .on('data', (row) => {
        students.push({
          sisId: row.sisId,
          name: row.name,
          email: row.email,
          phone: row.phone,
          class: row.class,
          year: row.year,
          rollNo: row.rollNo,
          enrollmentNo: row.enrollmentNo,
          branch: row.branch
          // password auto-generated by schema
        });
      })
      .on('end', async () => {
        try {
          await Student.insertMany(students, { ordered: false });

          fs.unlinkSync(req.file.path);

          res.status(201).json({
            message: "Students uploaded successfully",
            total: students.length
          });

        } catch (err) {
          res.status(500).json({
            message: "Some records may already exist",
            error: err.message
          });
        }
      });

  } catch (error) {
    res.status(500).json({
      message: error.message
    });
  }
});

router.get('/all', async (req, res) => {
  try {
    const students = await Student.find().sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: students.length,
      data: students
    });

  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
});

router.get('/export-csv', async (req, res) => {
  try {
    const students = await Student.find().select('-__v');

    if (!students.length) {
      return res.status(404).json({ message: "No students found" });
    }

    // Fields to export
    const fields = [
      'sisId',
      'name',
      'email',
      'phone',
      'class',
      'year',
      'rollNo',
      'enrollmentNo',
      'branch',
      'createdAt'
    ];

    const json2csvParser = new Parser({ fields });
    const csv = json2csvParser.parse(students);

    // Set headers
    res.header('Content-Type', 'text/csv');
    res.header('Content-Disposition', 'attachment; filename=students.csv');

    res.status(200).send(csv);

  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});


const path = require('path');

// 📌 Multer storage for student frames
const frameStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    const { studentId } = req.body;

    if (!studentId) {
      return cb(new Error("Student ID is required"), null);
    }

    const dir = `uploads/students/${studentId}`;

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    cb(null, dir);
  },

  filename: (req, file, cb) => {
    const filename = `frame_${Date.now()}_${Math.floor(Math.random() * 1000)}.jpg`;
    cb(null, filename);
  }
});

const uploadFrames = multer({ storage: frameStorage });


// ✅ ROUTE: STORE STUDENT FACE FRAMES
router.post(
  '/upload-frames',
  uploadFrames.array('frames', 20), // max 20 frames
  async (req, res) => {
    try {
      const { studentId } = req.body;

      if (!studentId) {
        return res.status(400).json({
          message: "Student ID is required"
        });
      }

      if (!req.files || req.files.length === 0) {
        return res.status(400).json({
          message: "No frames uploaded"
        });
      }

      res.status(200).json({
        message: "Frames uploaded successfully",
        studentId,
        totalFrames: req.files.length
      });

    } catch (error) {
      res.status(500).json({
        message: error.message
      });
    }
  }
);


//upload profile pic
const profileStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    const dir = 'uploads/students/profile';

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    cb(null, dir);
  },

  filename: (req, file, cb) => {
    const uniqueName =
      'student_' + Date.now() + path.extname(file.originalname);
    cb(null, uniqueName);
  }
});

const uploadProfile = multer({
  storage: profileStorage,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB
  fileFilter: (req, file, cb) => {
    if (
      file.mimetype === 'image/jpeg' ||
      file.mimetype === 'image/png'
    ) {
      cb(null, true);
    } else {
      cb(new Error("Only JPG & PNG allowed"));
    }
  }
});

router.post(
  '/upload-profile-photo/:studentId',
  uploadProfile.single('photo'),
  async (req, res) => {
    try {
      const { studentId } = req.params;

      if (!req.file) {
        return res.status(400).json({
          message: "No photo uploaded"
        });
      }

      const student = await Student.findById(studentId);

      if (!student) {
        return res.status(404).json({
          message: "Student not found"
        });
      }

      // Save image path to DB
      student.photo = req.file.path;
      await student.save();

      res.status(200).json({
        message: "Profile photo uploaded successfully",
        photo: student.photo
      });

    } catch (error) {
      res.status(500).json({
        message: error.message
      });
    }
  }
);


// ✅ GET STUDENT PROFILE DETAILS
router.get('/profile/:studentId', async (req, res) => {
  try {
    const { studentId } = req.params;

    const student = await Student.findById(studentId).select(
      'photo name branch rollNo phone email enrollmentNo'
    );

    if (!student) {
      return res.status(404).json({
        message: "Student not found"
      });
    }

    res.status(200).json({
      photo: student.photo,
      name: student.name,
      branch: student.branch,
      rollNo: student.rollNo,
      phone: student.phone,
      email: student.email,
      enrollmentNo: student.enrollmentNo
    });

  } catch (error) {
    res.status(500).json({
      message: error.message
    });
  }
});

module.exports = router;
